"use client";
import { useMemo, useState } from "react";
import { events, items, type OperationEvent } from "./demo-state";

type ItemId = (typeof items)[number]["id"];
const title = (event:string) => event.replaceAll("_", " ");
const labelFor = (status:string) => ({ EVIDENCE_COMPLETE:"CLEARED", SCOPE_MISMATCH:"SCOPE CONFLICT", AUTOMATION_PAUSED:"HUMAN HOLD", DOCUMENT_DEFICIENCY:"DOCUMENT DEFICIENCY", AWAITING_RESPONSE:"EVIDENCE NEEDED", UNDER_REVIEW:"IN REVIEW" }[status] ?? status);
function statusFor(id:ItemId, visible:OperationEvent[]) { const types=visible.filter(e=>e.item_id===id).map(e=>e.event_type); if(types.includes("ITEM_EVIDENCE_COMPLETE")) return "EVIDENCE_COMPLETE"; if(types.includes("SCOPE_MISMATCH_DETECTED")) return "SCOPE_MISMATCH"; if(types.includes("HUMAN_REVIEW_REQUESTED")&&!types.includes("CASE_RESUMED")) return "AUTOMATION_PAUSED"; if(types.includes("DOCUMENT_DEFICIENCY_FOUND")) return "DOCUMENT_DEFICIENCY"; if(types.includes("EVIDENCE_REQUESTED")) return "AWAITING_RESPONSE"; return "UNDER_REVIEW"; }
function ProductionHeader({visible}:{visible:OperationEvent[]}) { const unresolved=items.filter(item=>!['EVIDENCE_COMPLETE','SCOPE_MISMATCH'].includes(statusFor(item.id,visible))).length; return <header className="production-header"><div className="slate"><span>CF / 04</span><b>NIGHT SHIFT</b><span>Clearance operation</span></div><div className="status-rail"><span><strong>{items.filter(i=>statusFor(i.id,visible)==='EVIDENCE_COMPLETE').length}</strong> evidenced</span><span><strong>{unresolved}</strong> unresolved</span><span><strong>{visible.filter(e=>e.event_type==='HUMAN_REVIEW_REQUESTED').length}</strong> human gate</span><span className="latest">LATEST / {visible.at(-1)?.event_type?.replaceAll('_',' ') ?? 'READY'}</span></div></header> }
function ClearanceReel({selected,setSelected,visible}:{selected:ItemId;setSelected:(id:ItemId)=>void;visible:OperationEvent[]}) { return <section className="reel-zone"><div className="eyebrow">CLEARANCE REEL <span>Scene-linked evidence tickets</span></div><div className="reel-track"/>{items.map(item=>{const status=statusFor(item.id,visible);return <button key={item.id} className={`clearance-item ${status} ${selected===item.id?'selected':''}`} onClick={()=>setSelected(item.id)}><span className="scene">SCENE {item.scene}</span><b>{item.name}</b><small>{item.category}</small><mark>{status.replaceAll('_',' ')}</mark><i>{status==='AUTOMATION_PAUSED'?'⏸':'◉'}</i></button>})}</section> }
function EvidenceChain({id,visible,onResolve}:{id:ItemId;visible:OperationEvent[];onResolve:()=>void}) { const item=items.find(i=>i.id===id)!; const itemEvents=visible.filter(e=>e.item_id===id); const paused=statusFor(id,visible)==='AUTOMATION_PAUSED'; return <article className={`evidence-chain ${paused?'paused':''}`}><div className="eyebrow">EVIDENCE CHAIN <span>Recorded actions and evaluated records only</span></div><div className="chain-heading"><div><p>PRODUCTION USE</p><h1>{item.name}</h1><small>{item.use}</small></div><div className="chain-status">{labelFor(statusFor(id,visible))}</div></div><ol>{itemEvents.length?itemEvents.map((event,index)=><li key={event.sequence}><span>{String(index+1).padStart(2,'0')}</span><div><b>{title(event.event_type)}</b><p>{event.detail}</p>{event.evidence_id&&<small>REF / {event.evidence_id}</small>}</div></li>):<li><span>--</span><div><b>Awaiting operation</b><p>Run demo mode to reveal recorded clearance events.</p></div></li>}</ol>{paused&&<div className="human-gate"><div><b>⏸ AUTOMATION PAUSED</b><p>Human judgment required. ClearFrame cannot establish rights or permission scope from the recorded production still.</p></div><button onClick={onResolve}>Record human decision</button></div>}</article> }
function OperationsTape({visible,selected}:{visible:OperationEvent[];selected:ItemId}) { return <aside className="operations-tape"><div className="eyebrow">OPERATIONS TAPE <span>Persisted event stream</span></div><div className="tape-scroll">{visible.filter(e=>e.item_id===selected||selected==='daniel').map(event=><div className={`operation ${event.actor}`} key={event.sequence}><time>{event.recorded_at}</time><b>{event.actor}</b><div><strong>{title(event.event_type)}</strong><p>{event.detail}</p></div></div>)}</div><footer>Administrative evidence workflow. Not legal advice.</footer></aside> }
export default function Home(){const [cursor,setCursor]=useState(0);const [selected,setSelected]=useState<ItemId>('daniel');const visible=useMemo(()=>events.slice(0,cursor),[cursor]);const advance=()=>setCursor(v=>Math.min(events.length,v+1));const resolve=()=>setCursor(v=>Math.max(v,events.findIndex(e=>e.event_type==='CASE_RESUMED')+1));return <main><ProductionHeader visible={visible}/><div className="demo-controls"><span>DEMO MODE / {cursor} OF {events.length} RECORDED OPERATIONS</span><button onClick={advance} disabled={cursor===events.length}>Advance operation ↦</button><button className="quiet" onClick={()=>setCursor(events.length)}>Show completed run</button></div><ClearanceReel selected={selected} setSelected={setSelected} visible={visible}/><section className="workspace"><EvidenceChain id={selected} visible={visible} onResolve={resolve}/><OperationsTape visible={visible} selected={selected}/></section></main>}
