"use client";
import { useEffect, useMemo, useState } from "react";
import { items, type OperationEvent } from "./demo-state";

type ItemId = (typeof items)[number]["id"];
type Project = { events: OperationEvent[] };
const apiUrl = process.env.NEXT_PUBLIC_CLEARFRAME_API_URL ?? "http://localhost:8000";
const words = (s: string) => s.replaceAll("_", " ");
const status = (id: ItemId, e: OperationEvent[]) => { const t = e.filter(x => x.item_id === id).map(x => x.event_type); if (t.includes("ITEM_EVIDENCE_COMPLETE")) return "CLEARED"; if (t.includes("SCOPE_MISMATCH_DETECTED")) return "SCOPE CONFLICT"; if (t.includes("HUMAN_REVIEW_REQUESTED")) return t.includes("CASE_RESUMED") ? "HUMAN REVIEW" : "HUMAN HOLD"; if (t.includes("DOCUMENT_DEFICIENCY_FOUND")) return "DOCUMENT DEFICIENCY"; if (t.includes("EVIDENCE_REQUESTED")) return "EVIDENCE NEEDED"; return "IN REVIEW"; };
const kind = (id: ItemId) => ({ sarah: "performer", daniel: "performer", painting: "artwork", archive: "archive" }[id]);

function Header({ visible }: { visible: OperationEvent[] }) { const states = items.map(x => status(x.id, visible)); return <header><div className="production"><span>NIGHT SHIFT</span><small>SHORT FILM / CLEARANCE OPERATION</small></div><div className="summary"><span><b>{states.filter(x => x === "CLEARED").length}</b> CLEARED</span><span><b>{states.filter(x => x === "SCOPE CONFLICT").length}</b> CONFLICT</span><span><b>{states.filter(x => x.includes("HUMAN")).length}</b> HUMAN REVIEW</span></div><p>INTENDED USE / Worldwide · YouTube · Streaming · Festivals</p></header>; }
function AssetStrip({ selected, setSelected, visible }: { selected: ItemId; setSelected: (x: ItemId) => void; visible: OperationEvent[] }) { return <nav className="asset-strip" aria-label="Clearance subjects">{items.map(item => <button key={item.id} onClick={() => setSelected(item.id)} className={`${selected === item.id ? "selected" : ""} ${status(item.id, visible).replaceAll(" ", "-")}`}><span className={`frame ${kind(item.id)}`} aria-hidden="true"><i /></span><strong>{item.scene}</strong><div><b>{item.name}</b><small>{item.category}</small><mark>{status(item.id, visible)}</mark></div></button>)}</nav>; }
function Path({ id, visible, resolve }: { id: ItemId; visible: OperationEvent[]; resolve: () => Promise<void> }) { const item = items.find(x => x.id === id)!; const own = visible.filter(x => x.item_id === id); const state = status(id, visible); const isHuman = id === "painting" && own.some(x => x.event_type === "HUMAN_REVIEW_REQUESTED"); const evidence = own.filter(x => x.event_type === "DOCUMENT_RECEIVED").at(-1); const mismatch = own.find(x => x.event_type === "SCOPE_MISMATCH_DETECTED"); const decision = own.find(x => x.event_type === "HUMAN_DECISION_RECORDED"); return <section className="clearance-path"><div className="path-top"><div><span>SCENE {item.scene}</span><h1>{item.name}</h1><p>{item.category} · {item.use}</p></div><b className={`result ${state.replaceAll(" ", "-")}`}>{state}</b></div><div className="path-flow"><div className="path-node asset"><label>ASSET</label><b>{item.name}</b><span>{item.category}</span></div><div className="arrow">↓</div><div className="path-node"><label>EVIDENCE</label><b>{evidence ? evidence.detail : "No evidence received"}</b><span>{evidence?.evidence_id ? `REF / ${evidence.evidence_id}` : "Administrative record required"}</span></div><div className="arrow">↓</div>{isHuman ? <div className="human-gate"><label>HUMAN GATE</label><h2>AUTOMATION STOPS HERE</h2><p>Available evidence cannot establish the rights holder or usable permission scope. ClearFrame will not infer ownership.</p>{decision ? <><b>DECISION RECORDED</b><span>{decision.detail}</span><small>Workflow resumed by recorded human decision.</small></> : <button onClick={() => void resolve()}>Record human decision</button>}</div> : <><div className="path-node comparison"><label>RIGHTS / SCOPE ↔ PRODUCTION USE</label><b>{mismatch ? "Evidence exists, but does not cover intended use." : own.some(x => x.event_type === "EVIDENCE_MATCHED") ? "Evidence matched to declared use." : "Awaiting evidence evaluation."}</b><span>{mismatch?.detail ?? "Administrative evidence only — not a legal conclusion."}</span></div><div className="arrow">↓</div><div className="path-node final"><label>RESULT</label><b>{state}</b><span>{state === "CLEARED" ? "Declared production use supported." : state === "EVIDENCE NEEDED" ? "Agent has requested the required record." : "Continue through recorded workflow."}</span></div></>}</div></section>; }
const localTime = (recordedAt: string) => { const date = new Date(recordedAt); return Number.isNaN(date.getTime()) ? recordedAt : date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }); };
const assetLabel = (id: string) => { const item = items.find(candidate => candidate.id === id); return item ? `SCENE ${item.scene} · ${item.name}` : id; };
function Audit({ visible }: { visible: OperationEvent[] }) { return <aside className="audit audit-rail"><details><summary><span><b>PRODUCTION AUDIT</b><small>GLOBAL PRODUCTION TRAIL</small></span><span>{visible.length} RECORDED</span></summary><div className="audit-body">{visible.slice().reverse().map(x => <div className={`audit-row ${x.actor}`} key={x.sequence}><time dateTime={x.recorded_at} title={x.recorded_at}>{localTime(x.recorded_at)}</time><b>{x.actor}</b><div><strong>{words(x.event_type)}</strong><small><code>{x.event_type}</code> · {assetLabel(x.item_id)}{x.evidence_id ? ` · REF / ${x.evidence_id}` : ""}</small></div></div>)}<footer>Administrative evidence evaluation. Not legal advice.</footer></div></details></aside>; }

export default function Home() {
  const [project, setProject] = useState<Project | null>(null);
  const [selected, setSelected] = useState<ItemId>("archive");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const visible = useMemo(() => project?.events ?? [], [project]);
  const request = async (path: string, method = "GET", body?: unknown) => { setBusy(true); setError(null); try { const response = await fetch(`${apiUrl}${path}`, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Operation failed."); setProject(result); } catch (cause) { setError(cause instanceof Error ? cause.message : "Backend unavailable."); } finally { setBusy(false); } };
  useEffect(() => { void request("/api/project"); }, []);
  return <main><Header visible={visible}/><div className="controls"><span>DEMO RUN / {visible.length} RECORDED OPERATIONS</span>{error && <small className="api-error">{error}</small>}<button disabled={busy} onClick={() => void request("/api/demo/advance", "POST")}>Advance operation</button><button disabled={busy} onClick={() => void request("/api/demo/complete", "POST")}>Show completed run</button><button disabled={busy} onClick={() => void request("/api/demo/reset", "POST")}>Reset demo</button></div><AssetStrip selected={selected} setSelected={setSelected} visible={visible}/><div className="work"><Path id={selected} visible={visible} resolve={() => request("/api/human-decision", "POST", { decision: "Artwork will be removed from the final cut." })}/></div><Audit visible={visible}/></main>;
}
